#pragma once

#include <string>

enum class TokenKind
{
	TOKEN_IDENTIFIER,

	// assignment
	TOKEN_EQUALS,
	TOKEN_PLUS_EQUALS,
	TOKEN_MINUS_EQUALS,
	TOKEN_TIMES_EQUALS,
	TOKEN_DIVIDE_EQUALS,
	TOKEN_MODULO_EQUALS,
	TOKEN_BITWISE_AND_EQUALS,
	TOKEN_BITWISE_OR_EQUALS,
	TOKEN_BITWISE_XOR_EQUALS,
	TOKEN_BITWISE_L_SHIFT_EQUALS,
	TOKEN_BITWISE_R_SHIFT_EQUALS,

	// literals
	TOKEN_INT_LITERAL,
	TOKEN_FLOAT_LITERAL,
	TOKEN_STRING_LITERAL,

	// keywords
	TOKEN_TRUE,
	TOKEN_FALSE,
	TOKEN_CLASS,
	TOKEN_FN,
	TOKEN_RETURN,
	TOKEN_CONTINUE,
	TOKEN_BREAK,
	TOKEN_IF,
	TOKEN_ELSE,
	TOKEN_FOR,
	TOKEN_WHILE,
	TOKEN_OR,
	TOKEN_AND,
	TOKEN_NOT,
	TOKEN_NULL,
	TOKEN_VAR,
	TOKEN_IN,
	TOKEN_THIS,
	TOKEN_NEW,
	TOKEN_IMPORT,
	TOKEN_AS,

	// delimiters
	TOKEN_L_PAREN,
	TOKEN_R_PAREN,
	TOKEN_L_BRACE,   // '{'
	TOKEN_R_BRACE,   // '}'
	TOKEN_L_BRACKET, // '['
	TOKEN_R_BRACKET, // ']'
	TOKEN_COMMA,
	TOKEN_SEMICOLON,
	TOKEN_COLON,
	TOKEN_DOT,
	TOKEN_RANGE,

	// comparison
	TOKEN_LT,
	TOKEN_LTE,
	TOKEN_GT,
	TOKEN_GTE,
	TOKEN_NOT_EQUALITY,
	TOKEN_EQUALITY,

	// arithmetic
	TOKEN_PLUS,
	TOKEN_MINUS,
	TOKEN_ASTERISK,
	TOKEN_FORWARD_SLASH,
	TOKEN_MODULO,
	TOKEN_POWER,

	// bitwise
	TOKEN_BITWISE_OR,
	TOKEN_BITWISE_XOR,
	TOKEN_BITWISE_AND,
	TOKEN_BITWISE_L_SHIFT,
	TOKEN_BITWISE_R_SHIFT,
	TOKEN_BITWISE_NOT,

	TOKEN_INVALID,
	TOKEN_EOF
};

struct Token
{
	TokenKind kind;
	uint32_t line;
	uint32_t column;
	std::string tokenLiteral;
};